### ISSUE TITLE
Add functionality to allow per-annotator list of records assigned to each annotator

### ISSUE THREAD

**Issue by lilehman** [MIT-LCP/waveform-annotation#9]
Load the record assignment for each annotator from a CSV file.  
(The CSV record assignment file will be generated by another script that we run periodically.)

Record assignment file format:
Option 1: One CSV assignment file format, two-columns: <annotator_user_name,  record_name>
Option 2: one record assignment CSV file per annotator

**Comment by lilehman** [comment]
[Discussion/Question] Since the records will be assigned to annotators in batches with a due date associated with each assignment,  how do we keep track of the assignment date and due date? in the same annotator-record assignment mapping CSV file?  Or in a separate file or database?

[Organization of the annotator-record CSV mapping file]  Since there will be multiple datasets/folders for each project (e.g. GE,  demo-data, and later on DWC data), should we assume that each dataset folder will have one CSV file to define the annotator-record assignment for records in that particular folder?

**Comment by Lucas-Mc** [comment]
> [Discussion/Question] Since the records will be assigned to annotators in batches with a due date associated with each assignment, how do we keep track of the assignment date and due date? in the same annotator-record assignment mapping CSV file? Or in a separate file or database?

Hmmmm good question! It would be easy to keep it in the database so it can be easily manipulated and accessed, but I'm thinking about how to implement this. Maybe when the user selected the "I want to start annotating" or "I want more annotations" a timestamp is created for when that request was and also for when that request is due (something like two weeks later). If it's in the file, we would have to keep it updated by writing to it each time this request happens which might get confusing and more tedious.

> [Organization of the annotator-record CSV mapping file] Since there will be multiple datasets/folders for each project (e.g. GE, demo-data, and later on DWC data), should we assume that each dataset folder will have one CSV file to define the annotator-record assignment for records in that particular folder?

I think each dataset should have one mapping / assignment CSV file so that it makes more sense and we don't have to add another column stating which project the records and events belong to.

**Comment by Lucas-Mc** [comment]
Closed by #25
